version: "3.9"

services:
  producer:
    build:
      context: ./producer
      dockerfile: ./Dockerfile
    container_name: producer_service
    volumes:
      - ./producer:/app
    working_dir: /app
    command: python producers_orchestrator.py